### ISSUE TITLE
Onnx model gives incorrect classifications

### ISSUE THREAD

**Issue by colombod** [lobe/lobe.NET#6]
Using exported onnx can sometimes produces incorrect classification in comparison to tensorflow and lobe app.

**Comment by evolvedlight** [comment]
Did you find a solution? I have the same problem currently.

**Comment by colombod** [comment]
I was padding the image instead of center crop like the python code does. I changed the default behaviour to cropping and the problem is gone. The other change was to pick max classification from the list of confidences instead of the prediction and things seems better. What is that you are seeing? Are you using the latest version of the lobe .NET packages?

**Comment by evolvedlight** [comment]
Hi @colombod 

I just updated now to the latest version - I see a similar thing but actually I think it may just be due to the webcam library that I was using. I switched to giving the model images from the camera app and I don't get the same results. 

Thanks, you can close this, I'll have to work out why this webcam library is not working for me :)

Steve

**Comment by colombod** [comment]
What if you train using the camera lib to produce a set of images?
